version: '3.8'

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - todo-data:/app/nadb_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - todo-network

volumes:
  todo-data:
    driver: local

networks:
  todo-network:
    driver: bridge 